version: "3"
services:
  redis:
    platform: linux/amd64
    container_name: puddy-cache
    hostname: redis
    image: minwcho/puddy-cache:0.0.1
    ports:
      - "6379:6379"
  puddy:
    image: minwcho/puddy-backend:0.0.1
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: puddy-backend
    ports:
      - "8080:8080"
    depends_on:
      - redis